FROM node:22-alpine AS build
WORKDIR /app

ARG VITE_APP_TITLE="SRT Translate"
ARG VITE_DEFAULT_PROVIDER=claude
ARG VITE_CLAUDE_MODEL=claude-3-5-sonnet-latest
ARG VITE_OPENAI_ENDPOINT=https://api.openai.com/v1
ARG VITE_OPENAI_MODEL=gpt-4o-mini
ARG VITE_QWEN_MODEL=qwen-mt-turbo

ENV VITE_APP_TITLE=$VITE_APP_TITLE
ENV VITE_DEFAULT_PROVIDER=$VITE_DEFAULT_PROVIDER
ENV VITE_CLAUDE_MODEL=$VITE_CLAUDE_MODEL
ENV VITE_OPENAI_ENDPOINT=$VITE_OPENAI_ENDPOINT
ENV VITE_OPENAI_MODEL=$VITE_OPENAI_MODEL
ENV VITE_QWEN_MODEL=$VITE_QWEN_MODEL

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app

ENV PORT=3000

COPY --from=build /app/dist ./dist
COPY --from=build /app/server ./server

EXPOSE 3000

CMD ["node", "server/start.js", "--mode=production"]
